
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensiondetail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PensionDetail   
  template:
    metadata:
      labels:
        app: PensionDetail
    spec:
      containers:
      - name: pensiondetail
        image: pensionmanagement.azurecr.io/pensiondetail:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pensionerdetailsn

---
apiVersion: v1
kind: Service
metadata:
  name: pensiondetail
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PensionDetail